name: Maven_Build_Example
env:
  JAVA_VERSION : "17"
  DISTRIBUTION : "zulu"
  suiteXmlFile: "testSuites/tests.xml"
  BROWSER: "CHROME-REMOTE"
  LOGIN: "${{ secrets.LOGIN }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  URL: "https://www.advantageonlineshopping.com/#/"
on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Step 1 - Checkout master branch from Github
      uses: actions/checkout@v4

    - name: Step 2 - Build and run Docker Compose services
      run:  docker compose -f ./docker-compose.yml up -d

    - name: Step 3 - Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Step 4 - secret variable
      run: |
        echo "login is $LOGIN"
        echo "password is $PASSWORD" 

    - name: Step 5 - Build with Maven
      run:
        mvn clean test -DsuiteXmlFile="$suiteXmlFile" -Dbrowser="$BROWSER" -Durl="$URL" -Dlogin="$LOGIN" -Dpassword="$PASSWORD"

    - name: Step 6 - Tear down Docker Compose services
      run:
        docker compose down